import React from "react";
import {CartCounter} from "@/app/components/shopping-cart";
import {Metadata} from "next";

export const metadata: Metadata = {
	title: "Counter page server side",
	description: "Generated by server side",
};

export default function CounterPage() {
	return (
		<div className="bg-red-500  flex items-center justify-center flex-col w-full">
			<span className="text-black dark:text-white ">
				Productos en el carrito
			</span>
			<CartCounter value={30} />
		</div>
	);
}
